export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceBasic: process.env.STRIPE_PRICE_BASIC ?? "",
  stripePricePro: process.env.STRIPE_PRICE_PRO ?? "",
  stripePriceExtra: process.env.STRIPE_PRICE_EXTRA ?? "",
  emailHost: (process.env.EMAIL_HOST ?? "").trim(),
  emailPort: (process.env.EMAIL_PORT ?? "587").trim(),
  emailUser: (process.env.EMAIL_USER ?? "").trim(),
  emailPassword: (process.env.EMAIL_PASSWORD ?? "").trim(),
  emailFrom: (process.env.EMAIL_FROM ?? "").trim(),
};
